version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis_db
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra
    container_name: cassandra_db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true

  neo4j:
    image: neo4j:latest
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/superclave123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
